# Generated by Django 4.1.7 on 2023-05-09 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VetPlus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusquedaVeterinario_Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=20)),
                ('rut', models.IntegerField()),
            ],
        ),
    ]
